# Generated by Django 5.1.7 on 2025-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='znum',
            field=models.IntegerField(),
        ),
    ]
