# Generated by Django 5.1.7 on 2025-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_zipcode_znum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='znum',
            field=models.IntegerField(unique=True),
        ),
    ]
